### ISSUE TITLE
Fatal error: Call to a member function addHelperPath()

### ISSUE THREAD

**Issue by adehner** [omeka/plugin-UserProfiles#18]
I just installed version 1.1.1 of UserProfiles on Omeka 2.4.1. After creating a profile type and loading the public home page of my Omeka site, while logged in, I get the following error:

Fatal error: Call to a member function addHelperPath() on null in .../plugins/UserProfiles/UserProfilesPlugin.php on line 255

Do you have any idea what's going on here? Since I don't see this error reported in any existing issues, I'm wondering if this error is unique to my setup?

**Comment by zerocrates** [comment]
The likely culprit would be a theme problem. The `public_content_top` hook is supposed to pass along `$view`, like this: https://github.com/omeka/Omeka/blob/stable-2.4/application/views/scripts/common/header.php#L56

The hook is usually in your theme's common/header.php file.

**Comment by adehner** [comment]
That was it! 
For some reason the hook in my header file was missing the view portion: 
array('view'=>$this)

Thanks so much @zerocrates!!
